apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    release: cortex-tenant
    app.kubernetes.io/name: cortex-tenant
  name: cortex-tenant
  namespace: cortex
spec:
  replicas: 1
  selector:
    matchLabels:
      release: cortex-tenant
  template:
    metadata:
      labels:
        release: cortex-tenant
      namespace: cortex
    spec:
      containers:
        - image: ghcr.io/blind-oracle/cortex-tenant:latest
          imagePullPolicy: IfNotPresent
          name: cortex-tenant
          ports:
            - containerPort: 8080
              name: cortex-tenant
              protocol: TCP
          volumeMounts:
            - mountPath: /data/
              name: config-file
      volumes:
        - configMap:
            name: cortex-tenant-configmap
          name: config-file
