apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cortex-tenant
  name: cortex-tenant
  namespace: cortex
spec:
  ports:
    - name: cortex-tenant
      port: 8080
      protocol: TCP
      targetPort: cortex-tenant
    - name: http-metrics
      port: 9090
      targetPort: http-metrics
      protocol: TCP
  selector:
    release: cortex-tenant
