apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: cortex-tenant
  name: cortex-tenant
  namespace: cortex
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      path: /metrics
      port: http-metrics
  namespaceSelector:
    matchNames:
    - cortex
  selector:
    matchLabels:
      app.kubernetes.io/name: cortex-tenant